/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Error.java
 *
 * Created on Nov 4, 2009, 9:08:15 AM
 */

package aoinstaller;

import aoinstaller.gui.ConsoleRedirector;
import aoinstaller.gui.TextAreaWriter;
import aoinstaller.gui.StreamGobbler;
import java.io.InputStream;
import java.io.PrintStream;
import java.io.PrintWriter;
import org.jdesktop.application.Action;


/**
 *
 * @author nhoult
 */
public class Console extends javax.swing.JFrame {
//    private PrintStream ps = null;
//    private StreamGobbler sg = null;
    private ConsoleRedirector cr = null;
    private boolean error = false;
    
    /** Creates new form Error */
    public Console() {
        initComponents();

        cr = new ConsoleRedirector(textConsole);

        //InputStream is = new InputStream();
//        sg = new StreamGobbler(System.out,textConsole);

//        TextAreaWriter taw = new TextAreaWriter(textConsole);
//        System.setOut(new PrintStream(new OutputStream()));


        //ps = new PrintStream(
        //System.setOut(
    }

    @Action
    public void close(){
        if(error){
            System.exit(0);
        }
        this.setVisible(false);
    }
    
    public void setError(boolean error){
        this.error = error;
        if(error){
            this.setDefaultCloseOperation(Console.EXIT_ON_CLOSE);
        } else {
            this.setDefaultCloseOperation(Console.HIDE_ON_CLOSE);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textConsole = new javax.swing.JTextArea();
        buttonClose = new javax.swing.JButton();

        setName("Form"); // NOI18N

        jScrollPane1.setFocusable(false);
        jScrollPane1.setName("jScrollPane1"); // NOI18N

        textConsole.setColumns(20);
        textConsole.setEditable(false);
        textConsole.setRows(5);
        textConsole.setName("textConsole"); // NOI18N
        jScrollPane1.setViewportView(textConsole);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(aoinstaller.AoInstallerApp.class).getContext().getActionMap(Console.class, this);
        buttonClose.setAction(actionMap.get("close")); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(aoinstaller.AoInstallerApp.class).getContext().getResourceMap(Console.class);
        buttonClose.setText(resourceMap.getString("buttonClose.text")); // NOI18N
        buttonClose.setName("buttonClose"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonClose))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonClose))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Console().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClose;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textConsole;
    // End of variables declaration//GEN-END:variables

}
